---
  - name: My Playbook on worker-node1
    hosts: targetservers
    become: yes
    become_user: root
    tasks:
      - name: ensure apache is stopped
        service:
          name: httpd
          state: stopped
